import { Exceptions } from "../scripts/itemTypeHelpers";

export const allExceptions: Exceptions[] = [
  //body
  {
    itemId: 40,
    slotPosition: 0,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 132,
    slotPosition: 0,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 132,
    slotPosition: 0,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 132,
    slotPosition: 0,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 307,
    slotPosition: 0,
    side: "wearables-back",
    exceptionBool: true,
  },

  //face
  {
    itemId: 18,
    slotPosition: 1,
    side: "wearables-front",
    exceptionBool: true,
  },
  {
    itemId: 18,
    slotPosition: 1,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 18,
    slotPosition: 1,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 18,
    slotPosition: 1,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 55,
    slotPosition: 1,
    side: "wearables-front",
    exceptionBool: true,
  },
  {
    itemId: 55,
    slotPosition: 1,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 55,
    slotPosition: 1,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 140,
    slotPosition: 1,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 140,
    slotPosition: 1,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 216,
    slotPosition: 1,
    side: "wearables-front",
    exceptionBool: true,
  },
  {
    itemId: 216,
    slotPosition: 1,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 216,
    slotPosition: 1,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 240,
    slotPosition: 1,
    side: "wearables-front",
    exceptionBool: true,
  },
  {
    itemId: 240,
    slotPosition: 1,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 240,
    slotPosition: 1,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 306,
    slotPosition: 1,
    side: "wearables-front",
    exceptionBool: true,
  },
  {
    itemId: 306,
    slotPosition: 1,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 306,
    slotPosition: 1,
    side: "wearables-right",
    exceptionBool: true,
  },

  //eyes
  {
    itemId: 301,
    slotPosition: 2,
    side: "wearables-front",
    exceptionBool: true,
  },
  {
    itemId: 301,
    slotPosition: 2,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 301,
    slotPosition: 2,
    side: "wearables-right",
    exceptionBool: true,
  },

  {
    itemId: 66,
    slotPosition: 2,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 66,
    slotPosition: 2,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 66,
    slotPosition: 2,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 66,
    slotPosition: 2,
    side: "wearables-front",
    exceptionBool: true,
  },
  {
    itemId: 199,
    slotPosition: 2,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 199,
    slotPosition: 2,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 199,
    slotPosition: 2,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 199,
    slotPosition: 2,
    side: "wearables-front",
    exceptionBool: true,
  },
  {
    itemId: 14,
    slotPosition: 2,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 14,
    slotPosition: 2,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 36,
    slotPosition: 2,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 36,
    slotPosition: 2,
    side: "wearables-right",
    exceptionBool: true,
  },

  {
    itemId: 49,
    slotPosition: 2,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 49,
    slotPosition: 2,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 53,
    slotPosition: 2,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 53,
    slotPosition: 2,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 57,
    slotPosition: 2,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 57,
    slotPosition: 2,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 73,
    slotPosition: 2,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 73,
    slotPosition: 2,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 86,
    slotPosition: 2,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 86,
    slotPosition: 2,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 117,
    slotPosition: 2,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 117,
    slotPosition: 2,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 159,
    slotPosition: 2,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 159,
    slotPosition: 2,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 202,
    slotPosition: 2,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 202,
    slotPosition: 2,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 208,
    slotPosition: 2,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 208,
    slotPosition: 2,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 214,
    slotPosition: 2,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 214,
    slotPosition: 2,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 215,
    slotPosition: 2,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 215,
    slotPosition: 2,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 224,
    slotPosition: 2,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 224,
    slotPosition: 2,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 243,
    slotPosition: 2,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 243,
    slotPosition: 2,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 246,
    slotPosition: 2,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 246,
    slotPosition: 2,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 249,
    slotPosition: 2,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 249,
    slotPosition: 2,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 259,
    slotPosition: 2,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 259,
    slotPosition: 2,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 262,
    slotPosition: 2,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 262,
    slotPosition: 2,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 351,
    slotPosition: 2,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 351,
    slotPosition: 2,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 355,
    slotPosition: 2,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 355,
    slotPosition: 2,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 359,
    slotPosition: 2,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 359,
    slotPosition: 2,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 367,
    slotPosition: 2,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 367,
    slotPosition: 2,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 377,
    slotPosition: 2,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 377,
    slotPosition: 2,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 385,
    slotPosition: 2,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 385,
    slotPosition: 2,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 404,
    slotPosition: 2,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 404,
    slotPosition: 2,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 407,
    slotPosition: 2,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 407,
    slotPosition: 2,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 408,
    slotPosition: 2,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 408,
    slotPosition: 2,
    side: "wearables-right",
    exceptionBool: true,
  },

  //head

  {
    itemId: 27,
    slotPosition: 3,
    side: "wearables-front",
    exceptionBool: true,
  },
  {
    itemId: 27,
    slotPosition: 3,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 27,
    slotPosition: 3,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 27,
    slotPosition: 3,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 30,
    slotPosition: 3,
    side: "wearables-front",
    exceptionBool: true,
  },
  {
    itemId: 30,
    slotPosition: 3,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 30,
    slotPosition: 3,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 30,
    slotPosition: 3,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 33,
    slotPosition: 3,
    side: "wearables-front",
    exceptionBool: true,
  },
  {
    itemId: 33,
    slotPosition: 3,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 33,
    slotPosition: 3,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 33,
    slotPosition: 3,
    side: "wearables-back",
    exceptionBool: true,
  },

  {
    itemId: 72,
    slotPosition: 3,
    side: "wearables-front",
    exceptionBool: true,
  },
  {
    itemId: 72,
    slotPosition: 3,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 72,
    slotPosition: 3,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 72,
    slotPosition: 3,
    side: "wearables-back",
    exceptionBool: true,
  },

  {
    itemId: 144,
    slotPosition: 3,
    side: "wearables-front",
    exceptionBool: true,
  },
  {
    itemId: 144,
    slotPosition: 3,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 144,
    slotPosition: 3,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 144,
    slotPosition: 3,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 145,
    slotPosition: 3,
    side: "wearables-front",
    exceptionBool: true,
  },
  {
    itemId: 145,
    slotPosition: 3,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 145,
    slotPosition: 3,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 145,
    slotPosition: 3,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 161,
    slotPosition: 3,
    side: "wearables-front",
    exceptionBool: true,
  },
  {
    itemId: 161,
    slotPosition: 3,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 161,
    slotPosition: 3,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 161,
    slotPosition: 3,
    side: "wearables-back",
    exceptionBool: true,
  },

  {
    itemId: 242,
    slotPosition: 3,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 242,
    slotPosition: 3,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 242,
    slotPosition: 3,
    side: "wearables-back",
    exceptionBool: true,
  },

  {
    itemId: 292,
    slotPosition: 3,
    side: "wearables-front",
    exceptionBool: true,
  },
  {
    itemId: 292,
    slotPosition: 3,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 292,
    slotPosition: 3,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 292,
    slotPosition: 3,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 302,
    slotPosition: 3,
    side: "wearables-front",
    exceptionBool: true,
  },
  {
    itemId: 302,
    slotPosition: 3,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 302,
    slotPosition: 3,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 302,
    slotPosition: 3,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 308,
    slotPosition: 3,
    side: "wearables-front",
    exceptionBool: true,
  },
  {
    itemId: 308,
    slotPosition: 3,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 308,
    slotPosition: 3,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 308,
    slotPosition: 3,
    side: "wearables-back",
    exceptionBool: true,
  },

  //right hand
  {
    itemId: 23,
    slotPosition: 4,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 23,
    slotPosition: 4,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 201,
    slotPosition: 4,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 201,
    slotPosition: 4,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 201,
    slotPosition: 4,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 217,
    slotPosition: 4,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 217,
    slotPosition: 4,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 217,
    slotPosition: 4,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 223,
    slotPosition: 4,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 223,
    slotPosition: 4,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 223,
    slotPosition: 4,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 312,
    slotPosition: 4,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 312,
    slotPosition: 4,
    side: "wearables-right",
    exceptionBool: true,
  },

  //left hand
  {
    itemId: 23,
    slotPosition: 5,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 23,
    slotPosition: 5,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 201,
    slotPosition: 5,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 201,
    slotPosition: 5,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 201,
    slotPosition: 5,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 217,
    slotPosition: 5,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 217,
    slotPosition: 5,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 217,
    slotPosition: 5,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 223,
    slotPosition: 5,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 223,
    slotPosition: 5,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 223,
    slotPosition: 5,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 312,
    slotPosition: 5,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 312,
    slotPosition: 5,
    side: "wearables-right",
    exceptionBool: true,
  },

  //pet
  {
    itemId: 151,
    slotPosition: 6,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 152,
    slotPosition: 6,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 153,
    slotPosition: 6,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 154,
    slotPosition: 6,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 155,
    slotPosition: 6,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 156,
    slotPosition: 6,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 233,
    slotPosition: 6,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 236,
    slotPosition: 6,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 237,
    slotPosition: 6,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 238,
    slotPosition: 6,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 261,
    slotPosition: 6,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 305,
    slotPosition: 6,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 201,
    slotPosition: 4,
    exceptionBool: true,
    side: "wearables-right",
  },
  {
    itemId: 217,
    slotPosition: 4,
    exceptionBool: true,
    side: "wearables-right",
  },
  {
    itemId: 223,
    slotPosition: 4,
    exceptionBool: true,
    side: "wearables-right",
  },
  {
    itemId: 201,
    slotPosition: 5,
    exceptionBool: true,
    side: "wearables-left",
  },
  {
    itemId: 217,
    slotPosition: 5,
    exceptionBool: true,
    side: "wearables-left",
  },
  {
    itemId: 223,
    slotPosition: 5,
    exceptionBool: true,
    side: "wearables-left",
  },
  {
    itemId: 261,
    slotPosition: 6,
    exceptionBool: true,
    side: "wearables-back",
  },
  {
    itemId: 151,
    slotPosition: 6,
    exceptionBool: true,
    side: "wearables-back",
  },
  {
    itemId: 152,
    slotPosition: 6,
    exceptionBool: true,
    side: "wearables-back",
  },

  {
    itemId: 153,
    slotPosition: 6,
    exceptionBool: true,
    side: "wearables-back",
  },
  {
    itemId: 154,
    slotPosition: 6,
    exceptionBool: true,
    side: "wearables-back",
  },
  {
    itemId: 155,
    slotPosition: 6,
    exceptionBool: true,
    side: "wearables-back",
  },
  {
    itemId: 156,
    slotPosition: 6,
    exceptionBool: true,
    side: "wearables-back",
  },
  {
    itemId: 353,
    slotPosition: 6,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 361,
    slotPosition: 6,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 374,
    slotPosition: 6,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 371,
    slotPosition: 1,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 371,
    slotPosition: 1,
    side: "wearables-right",
    exceptionBool: true,
  },

  {
    itemId: 306,
    slotPosition: 1,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 306,
    slotPosition: 1,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 381,
    slotPosition: 2,
    side: "wearables-right",
    exceptionBool: true,
  },
  {
    itemId: 381,
    slotPosition: 2,
    side: "wearables-left",
    exceptionBool: true,
  },
  {
    itemId: 381,
    slotPosition: 2,
    side: "wearables-front",
    exceptionBool: true,
  },
  {
    itemId: 406,
    slotPosition: 6,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 410,
    slotPosition: 6,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 413,
    slotPosition: 6,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 415,
    slotPosition: 6,
    side: "wearables-back",
    exceptionBool: true,
  },
  {
    itemId: 417,
    slotPosition: 6,
    side: "wearables-back",
    exceptionBool: true,
  },
];
